openapi: 3.0.0
info:
  description: Nudm Context Management Service
  title: Nudm_UECM
  version: 1.PreR15.0.0
externalDocs:
  description: Documentation
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
servers:
- url: https://{apiRoot}/nudm-uecm/v1
  variables:
    apiRoot:
      default: https://demohost.com
      description: apiRoot as defined in subclause subclause 4.4 of 3GPP TS 29.501,
        excluding the https:// part.
security:
- oAuth2ClientCredentials: []
paths:
  /{ueId}/registrations/amf-3gpp-access:
    get:
      operationId: Get
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Gpsi'
        style: simple
      - explode: true
        in: query
        name: supportedFeatures
        required: false
        schema:
          $ref: '#/components/schemas/SupportedFeatures'
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Amf3GppAccessRegistration'
          description: Expected response to a valid request
        404:
          description: User (GPSI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: retrieve the AMF registration for 3GPP access information
      tags:
      - AMF 3Gpp-access Registration Info Retrieval
    patch:
      operationId: Update
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Amf3GppAccessRegistrationModification'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: Update a parameter in the AMF registration for 3GPP access
      tags:
      - Parameter update in the AMF registration for 3GPP access
    put:
      callbacks:
        deregistrationeNotification:
          '{request.body#/deregCallbackUri}':
            post:
              operationId: deregistrationeNotification_request_bodyDeregCallbackUriPost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/DeregistrationData'
                required: true
              responses:
                204:
                  description: Successful Notification response
              x-callback-request: true
      operationId: Registration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amf3GppAccessRegistration'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: register as AMF for 3GPP access
      tags:
      - AMF registration for 3GPP access
  /{ueId}/registrations/amf-non-3gpp-access:
    get:
      operationId: Get
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Gpsi'
        style: simple
      - explode: true
        in: query
        name: supportedFeatures
        required: false
        schema:
          $ref: '#/components/schemas/SupportedFeatures'
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
          description: Expected response to a valid request
        404:
          description: User (GPSI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: retrieve the AMF registration for non-3GPP access information
      tags:
      - AMF non-3GPP-access Registration Info  Retrieval
    patch:
      operationId: Update
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/AmfNon3GppAccessRegistrationModification'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: update a parameter in the AMF registration for non-3GPP access
      tags:
      - Parameter update in the AMF registration for non-3GPP access
    put:
      callbacks:
        deregistrationeNotification:
          '{request.body#/deregCallbackUri}':
            post:
              operationId: deregistrationeNotification_request_bodyDeregCallbackUriPost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/DeregistrationData'
                required: true
              responses:
                204:
                  description: Successful Notification response
              x-callback-request: true
      operationId: Register
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmfNon3GppAccessRegistration'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: register as AMF for non-3GPP access
      tags:
      - AMF registration for non-3GPP access
  /{ueId}/registrations/smf-registrations/{pduSessionId}:
    delete:
      operationId: Deregistration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      - description: Identifier of the PDU session
        explode: false
        in: path
        name: pduSessionId
        required: true
        schema:
          $ref: '#/components/schemas/PduSessionId'
        style: simple
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: delete an SMF registration
      tags:
      - SMF Deregistration
    put:
      callbacks:
        pcscfRestorationNotification:
          '{request.body#/pcscfRestorationCallbackUri}':
            post:
              operationId: pcscfRestorationNotification_request_bodyPcscfRestorationCallbackUriPost
              requestBody:
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PcscfRestorationNotification'
                required: true
              responses:
                204:
                  description: Successful Notification response
              x-callback-request: true
      operationId: Registration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      - description: Identifier of the PDU session
        explode: false
        in: path
        name: pduSessionId
        required: true
        schema:
          $ref: '#/components/schemas/PduSessionId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmfRegistration'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmfRegistration'
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: register as SMF
      tags:
      - SMF Registration
  /{ueId}/registrations/smsf-3gpp-access:
    delete:
      operationId: Deregistration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: delete the SMSF registration for 3GPP access
      tags:
      - SMSF Deregistration for 3GPP Access
    get:
      operationId: Get
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Gpsi'
        style: simple
      - explode: true
        in: query
        name: supportedFeatures
        required: false
        schema:
          $ref: '#/components/schemas/SupportedFeatures'
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsfRegistration'
          description: Expected response to a valid request
        404:
          description: User (GPSI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: retrieve the SMSF registration for 3GPP access information
      tags:
      - SMSF 3GPP access Registration Info Retrieval
    put:
      operationId: Update SMSF Reg 3GPP
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsfRegistration'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: register as SMSF for 3GPP access
      tags:
      - SMSF registration for 3GPP access
  /{ueId}/registrations/smsf-non-3gpp-access:
    delete:
      operationId: Deregistration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: delete SMSF registration for non 3GPP access
      tags:
      - SMSF Deregistration for non-3GPP access
    get:
      operationId: Get
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Gpsi'
        style: simple
      - explode: true
        in: query
        name: supportedFeatures
        required: false
        schema:
          $ref: '#/components/schemas/SupportedFeatures'
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsfRegistration'
          description: Expected response to a valid request
        404:
          description: User (GPSI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: retrieve the SMSF registration for non-3GPP access information
      tags:
      - SMSF non-3GPP access Registration Info Retrieval
    put:
      operationId: Registration
      parameters:
      - description: Identifier of the UE
        explode: false
        in: path
        name: ueId
        required: true
        schema:
          $ref: '#/components/schemas/Supi'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsfRegistration'
        required: true
      responses:
        204:
          description: Expected response to a valid request
        404:
          description: User (SUPI) does not exist
        default:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unexpected error
      summary: register as SMSF for non-3GPP access
      tags:
      - SMSF registration for non-3GPP access
components:
  schemas:
    Amf3GppAccessRegistration:
      example:
        deregCallbackUri: deregCallbackUri
        supportedFeatures: supportedFeatures
        purgeFlag: true
        pei: pei
        pcscfRestorationCallbackUri: pcscfRestorationCallbackUri
        amfId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        amfId:
          format: uuid
          type: string
        supportedFeatures:
          pattern: ^[A-Fa-f0-9]*$
          type: string
        purgeFlag:
          type: boolean
        pei:
          pattern: ^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
          type: string
        imsVoPS:
          $ref: '#/components/schemas/ImsVoPS'
        deregCallbackUri:
          type: string
        pcscfRestorationCallbackUri:
          type: string
      required:
      - amfId
      - deregCallbackUri
      type: object
    Amf3GppAccessRegistrationModification:
      properties:
        purgeFlag:
          type: boolean
        pei:
          pattern: ^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
          type: string
        imsVoPS:
          $ref: '#/components/schemas/ImsVoPS'
      type: object
    AmfNon3GppAccessRegistration:
      example:
        deregCallbackUri: deregCallbackUri
        supportedFeatures: supportedFeatures
        purgeFlag: true
        pei: pei
        pcscfRestorationCallbackUri: pcscfRestorationCallbackUri
        amfId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        amfId:
          format: uuid
          type: string
        supportedFeatures:
          pattern: ^[A-Fa-f0-9]*$
          type: string
        purgeFlag:
          type: boolean
        pei:
          pattern: ^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
          type: string
        deregCallbackUri:
          type: string
        pcscfRestorationCallbackUri:
          type: string
      required:
      - amfId
      - deregCallbackUri
      type: object
    AmfNon3GppAccessRegistrationModification:
      properties:
        purgeFlag:
          type: boolean
        pei:
          pattern: ^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
          type: string
      type: object
    SmfRegistration:
      example:
        smfId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        supportedFeatures: supportedFeatures
        dnn: dnn
        pcscfRestorationCallbackUri: pcscfRestorationCallbackUri
        pduSessionId: 20
      properties:
        smfId:
          format: uuid
          type: string
        supportedFeatures:
          pattern: ^[A-Fa-f0-9]*$
          type: string
        pduSessionId:
          format: int32
          maximum: 255
          minimum: 0
          type: integer
        dnn:
          type: string
        pcscfRestorationCallbackUri:
          type: string
      required:
      - dnn
      - pduSessionId
      - smfId
      type: object
    SmsfRegistration:
      example:
        supportedFeatures: supportedFeatures
        smsfId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        smsfId:
          format: uuid
          type: string
        supportedFeatures:
          pattern: ^[A-Fa-f0-9]*$
          type: string
      required:
      - smsfId
      type: object
    DeregistrationData:
      example: {}
      properties:
        deregReason:
          $ref: '#/components/schemas/DeregistrationReason'
      required:
      - deregReason
      type: object
    PcscfRestorationNotification:
      example:
        supi: supi
      properties:
        supi:
          format: Supi
          pattern: ^(imsi-[0-9]{5,15}|nai-.+|.+)$
          type: string
      required:
      - supi
      type: object
    PurgeFlag:
      type: boolean
    ImsVoPS:
      anyOf:
      - enum:
        - HOMOGENEOUS_SUPPORT
        - HOMOGENEOUS_NON_SUPPORT
        - NON_HOMOGENEOUS_OR_UNKNOWN
        type: string
      - type: string
    DeregistrationReason:
      anyOf:
      - enum:
        - UE_INITIAL_REGISTRATION
        - UE_REGISTRATION_AREA_CHANGE
        - SUBSCRIPTION_WITHDRAWN
        - 5GS_TO_EPS_MOBILITY
        type: string
      - type: string
    Gpsi:
      pattern: ^(msisdn-[0-9]{5,15}|extid-.+|.+)$
      type: string
    SupportedFeatures:
      pattern: ^[A-Fa-f0-9]*$
      type: string
    ProblemDetails:
      properties:
        type:
          type: string
        title:
          type: string
        status:
          format: int32
          type: integer
        instance:
          type: string
        cause:
          type: string
        invalidParams:
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 0
          type: array
      type: object
    Uri:
      type: string
    InvalidParam:
      properties:
        param:
          type: string
        reason:
          type: string
      required:
      - param
      type: object
    Supi:
      format: Supi
      pattern: ^(imsi-[0-9]{5,15}|nai-.+|.+)$
      type: string
    PduSessionId:
      format: int32
      maximum: 255
      minimum: 0
      type: integer
    NfInstanceId:
      format: uuid
      type: string
    Pei:
      pattern: ^(imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
      type: string
    Dnn:
      type: string
  securitySchemes:
    oAuth2ClientCredentials:
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
      type: oauth2
